name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Create Release
        uses: tristanpoland/Rust-Release-Action@0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
